---
- name: requirements
  include_tasks: requirements.yml

- name: services
  vars:
   service: "{{ item }}"
  include_tasks: "{{ item }}.yml"
  tags:
    - backup
  with_items:
    - "{{ backup_services }}"
