---
- name: backup | add command aliases
  template:
    src: profile-backup.sh.j2
    dest: /etc/profile.d/backup.sh
    owner: root
    group: root
    mode: 0640

- name: backup | add last backup check script
  template:
    src: check_duplicity.sh.j2
    dest: /usr/local/bin/check_duplicity.sh
    owner: root
    group: root
    mode: 0750
